Task16
DenisTDA/tutu pull request #2
Opened 2017-05-27 10:11 UTC by DenisTDA

Задание 16.

2017-05-27 14:18 UTC, DenisTDA commented
Исправляю маленькую ошибку

2017-05-27 14:20 UTC, DenisTDA commented
Исправил

2017-05-27 14:21 UTC, DenisTDA commented
Путаюсь..

2017-05-27 14:23 UTC, DenisTDA commented on app/controllers/carriages_controller.rb
> +      redirect_to @trainб notice: 'Вагон успешно создан'
тут запятая... опечатался.

2017-05-28 08:13 UTC, iBublik requested changes

2017-05-28 08:13 UTC, iBublik commented on config/routes.rb
> +    resources :carriages
Тут ты немного опередил события - это будет в следующем занятии :)

2017-05-28 08:13 UTC, iBublik commented on app/controllers/carriages_controller.rb
> +      redirect_to @trainб notice: 'Вагон успешно создан'
Наверно, тут должна быть запятая

2017-05-28 08:13 UTC, iBublik commented on app/controllers/carriages_controller.rb
> +    params.require(:carriage).permit(:number, :train_id, :top,
Раз уже сделал ресурс вагонов вложенным в поезда, то зачем разрешать передавать train_id? `@train.carriages.new` привяжет вагон к нужному поезду

2017-05-28 08:13 UTC, iBublik commented on app/controllers/railway_stations_controller.rb
> +  def update_station
Слишком общее название экшена - непонятно в чем отличие от `update`

2017-05-28 08:13 UTC, iBublik commented on app/controllers/railway_stations_controller.rb
> +  def update_station
И вообще в этом задании можно было не делать этого экшена. Ты это у других подглядел? Не надо бежать впереди паровоза и слепо копировать, лучше сделай строго по заданию, но разберись что и как, а то будет поверхностное понимание.

2017-05-28 08:13 UTC, iBublik commented on app/controllers/routes_controller.rb
> +    @route.ordering
Зачем тут происходит вызов этого метода?

2017-05-28 08:13 UTC, iBublik commented on app/controllers/routes_controller.rb
> +    @route.ordering
И тут тоже непонятно зачем

2017-05-28 08:13 UTC, iBublik commented on app/models/carriage.rb
> +  # validates :kind, presence: true
Не нужно оставлять неиспользуемый код

2017-05-28 08:13 UTC, iBublik commented on app/models/carriage.rb
> +  scope :sort_up, -> { order(number: :asc) }
Лучше сделать один скоуп с параметром, в зависимости от которого будет происходить нужная сортировка

2017-05-28 08:13 UTC, iBublik commented on app/models/carriage.rb
> +  def set_number
Код получился довольно запутанным. Можно сделать намного проще - просто посчитать число вагонов в поезде и к этому значению прибавить 1.

2017-05-28 08:13 UTC, iBublik commented on app/models/carriage.rb
> +        self.number ||= i
Заметь - все эти подсчеты выполняются, хотя нам может и вовсе не придется утснавливать номер вагона, т.к. он уже есть. Это избыточные действия, лучше сразу ничего не делать, если номер уже присвоен

2017-05-28 08:13 UTC, iBublik commented on app/models/compart_carriage.rb
> +  validates :top, :bottom, presence: true
В именах явно не хватает указания, что это _места_. Сам подумай, ты смотришь код и видишь `carraige.top` - что означает эта величина? Это замечание относится ко всем классам вагонов

2017-05-28 08:13 UTC, iBublik commented on app/models/railway_station.rb
> +  def update_position(route, position)
Опять код, которого не должно быть в этом задании.

2017-05-28 08:13 UTC, iBublik commented on app/models/railway_station.rb
> +  def position(route)
Это тоже не из этого задания

2017-05-28 08:13 UTC, iBublik commented on app/models/route.rb
> +  def ordering
Зачем вообще нужен этот метод?

2017-05-28 08:13 UTC, iBublik commented on app/models/train.rb
> +  def sort_carriages
Лучше назвать `sorted_carriages` - этот метод является запросом (просто считывает данные), а не командой (команды меняют данные). Иначе создается впечатление, что ты как-то меняешь порядок вагонов, хотя это не так

2017-05-28 08:13 UTC, iBublik commented on app/models/train.rb
> +    direct_sort ? carriages.sort_up : carriages.sort_down
`carriages.sorted(direct_sort)` было бы лучше :)

2017-05-28 08:13 UTC, iBublik commented on app/views/carriages/_carriage.html.erb
> +<%= yield :car%>
Проще тут рендерить патиал по типу вагона, а то сейчас просто каша какая-то

2017-05-28 08:13 UTC, iBublik commented on app/views/carriages/compart_carriage.html.erb
> +<%= render 'carriage', carriage: @carriage %>
И тут снова вызов партиала.. Я, если честно, вообще запутался :) А еще непонятно зачем ты передаешь в партиал локальную переменную, если внутри него все равно работаешь с инстанс переменной

2017-05-28 08:13 UTC, iBublik commented on app/views/carriages/compart_carriage.html.erb
> +<%= render 'carriage', carriage: @carriage %>
Это вообще работает? Ты рендеришь партиал внутри `content_for`,  а в нем делаешь `yield :car`. В общем крайне запутанное решение, без поллитры не разберешься :)

2017-05-28 08:13 UTC, iBublik commented on app/views/carriages/index.html.erb
> +    <%= render partial: 'carriages/carriage', collection: @carriages %>
`render @carriages` то же самое сделает

2017-05-28 08:13 UTC, iBublik commented on app/views/routes/show.html.erb
> +      <%= form_tag(update_station_railway_station_path(station), method: "put") do %>
Это лишнее, в следующем уроке будем это проходить. Сконцентрируйся на решении проблем из текщего задания

2017-05-28 08:13 UTC, iBublik commented on db/migrate/20170516163917_add_type_carriage_number_to_carriages.rb
> +    add_column :carriages, :side_top, :integer
Когда много изменений в одну таблицу вносишь, лучше использовать `change_table :carriages do |t| ... end`

2017-05-28 08:13 UTC, iBublik commented on db/migrate/20170521193739_add_direct_sort_to_trains.rb
> +    add_column :trains, :direct_sort, :boolean
`default: false, null: false` - иначе будут `null`-ы стоять в поле

2017-05-28 09:33 UTC, DenisTDA commented on app/controllers/railway_stations_controller.rb
> +  def update_station
Вообще то, данный метод обсуждался в ветке по этому заданию, где Виталий и предложил реализацию сортировки вагонов. Все задания я делал сам, исходя исключительно из своих соображений. Вложенный ресурс мне предложил Паша, когда я к нему обратился за помощью. И про него я прочитал и разобрался в той степени, чтобы выполнить 16 задание.

2017-05-28 09:39 UTC, DenisTDA commented on app/controllers/routes_controller.rb
> +    @route.ordering
потому как без него не устанавливается поле position, т.е. сортировка станций.. если поле пустое (а на нем стоит валидация уникальности), то возникают несколько станций с одинаковым значением, отсюда вываливается ошибка. Т.е. нужно первичное назначение порядка, что и делает этот метод.

2017-05-28 09:41 UTC, DenisTDA commented on app/controllers/routes_controller.rb
> +    @route.ordering
аналогично вышеприведенному объяснению, при добавлении сразу нескольких станций, возникает несколько одинаковых значений.

2017-05-28 09:43 UTC, DenisTDA commented on app/models/carriage.rb
> +  # validates :kind, presence: true
Да я "за". Но в 3 часа ночи некоторые вещи уже не видишь. :-)

2017-05-28 09:43 UTC, iBublik commented on app/controllers/railway_stations_controller.rb
> +  def update_station
Возможно, на ранних стадиях курса это было в этом задании, но сейчас перекочевало в следующий урок.

2017-05-28 09:43 UTC, DenisTDA commented on app/models/carriage.rb
> +  scope :sort_up, -> { order(number: :asc) }
ок

2017-05-28 09:44 UTC, DenisTDA commented on app/models/carriage.rb
> +  def set_number
нет! Читай комментарии Виталия! Он точно обозначил, что так нельзя!

2017-05-28 09:47 UTC, DenisTDA commented on app/models/compart_carriage.rb
> +  validates :top, :bottom, presence: true
Про этот метод тоже Виталий писал.

2017-05-28 09:48 UTC, DenisTDA commented on app/models/railway_station.rb
> +  def update_position(route, position)
Тоже про этот метод Виталий писал в ветке

2017-05-28 09:49 UTC, iBublik commented on app/controllers/routes_controller.rb
> +    @route.ordering
Обычно такие вопросы решаются коллбэками, как мы сделали с вагонами в поезде.

2017-05-28 09:52 UTC, DenisTDA commented on app/models/railway_station.rb
> +  def position(route)
Из этого или не из этого, я не знаю. Я пытался при апдейт получить позицию станции. Но потом пошел другим путем. Метод забыл удалить

2017-05-28 09:53 UTC, DenisTDA commented on app/models/route.rb
> +  def ordering
читай выше

2017-05-28 09:53 UTC, DenisTDA commented on app/models/train.rb
> +  def sort_carriages
ок

2017-05-28 09:55 UTC, iBublik commented on app/models/carriage.rb
> +  def set_number
Нашел, каюсь :) но есть другой вариант, тоже проще твоего - нужно найти максимальный номер вагона у поезда и прибавить 1

2017-05-28 09:59 UTC, DenisTDA commented on app/models/train.rb
> +    direct_sort ? carriages.sort_up : carriages.sort_down
ок

2017-05-28 10:02 UTC, DenisTDA commented on app/views/carriages/_carriage.html.erb
> +<%= yield :car%>
Первое чего я добивался - это уменьшить повторяющегося кода, второе - стало интересно, можно внедрить одно в другое.

2017-05-28 10:03 UTC, DenisTDA commented on app/views/carriages/compart_carriage.html.erb
> +<%= render 'carriage', carriage: @carriage %>
О да!!! это работает! я все проверял! почему долго и делал..

2017-05-28 10:07 UTC, DenisTDA commented on app/views/carriages/index.html.erb
> +    <%= render partial: 'carriages/carriage', collection: @carriages %>
Артем! прочитай мои комменты в отчетах.

2017-05-28 10:10 UTC, DenisTDA commented on app/views/routes/show.html.erb
> +      <%= form_tag(update_station_railway_station_path(station), method: "put") do %>
опять же Виталий писал в ветке по выполнению задания. ЭТОГО задания!

2017-05-28 10:11 UTC, DenisTDA commented on db/migrate/20170516163917_add_type_carriage_number_to_carriages.rb
> +    add_column :carriages, :side_top, :integer
угу, учту

2017-05-28 10:11 UTC, DenisTDA commented on db/migrate/20170521193739_add_direct_sort_to_trains.rb
> +    add_column :trains, :direct_sort, :boolean
ок. учту

2017-05-28 10:12 UTC, DenisTDA commented
:-) вообщем, почти ни с чем не согласился. Что делать дальше? Либо вразумите, либо утвердите задание. Жду ответа.

2017-05-28 10:14 UTC, DenisTDA commented on app/controllers/carriages_controller.rb
> +      redirect_to @trainб notice: 'Вагон успешно создан'
самый верхний мой коммент...

2017-05-28 10:15 UTC, DenisTDA commented on app/controllers/carriages_controller.rb
> +    params.require(:carriage).permit(:number, :train_id, :top,
Я так устал делать это задание, что на такие вещи уже перестал обращать внимание. Согласен, дурак, исправлюсь.

2017-05-28 10:17 UTC, iBublik commented on app/views/routes/show.html.erb
> +      <%= form_tag(update_station_railway_station_path(station), method: "put") do %>
Я руководствуюсь текстом задания 
> Пока установку порядкового номера сделать без веб-интерфейса, можно это делать через rails-консоль
Так же в видео следующего урока как раз разбирается установка номера для маршрута. В общем призываю @vkurennov, т.к. явно путаница возникла

2017-05-28 10:18 UTC, iBublik commented on app/views/carriages/index.html.erb
> +    <%= render partial: 'carriages/carriage', collection: @carriages %>
В отчете я написал, что тогда этот код надо удалить. Зачем оставлять неиспользуемые куски?

2017-05-28 10:20 UTC, DenisTDA commented on app/controllers/railway_stations_controller.rb
> +  def update_station
вот что даете в дополнительных материалах, то и читаем http://thinknetica.teachbase.ru/course_sessions/25475/take#id=83615 самая первая ссылка

2017-05-28 10:21 UTC, DenisTDA commented on app/controllers/routes_controller.rb
> +    @route.ordering
я подумаю..

2017-05-28 10:29 UTC, DenisTDA commented on app/models/carriage.rb
> +  def set_number
тогда внутри состава будут пропуски в номерах. А еслу удалят 60-70 процентов вагонов, а потом добавят? я считаю, что я сделал оптимально, а самое главное по заданию :-)

2017-05-28 10:30 UTC, DenisTDA commented on app/views/carriages/index.html.erb
> +    <%= render partial: 'carriages/carriage', collection: @carriages %>
:-) так я больше и не коммитил.. :-)

2017-05-28 10:31 UTC, DenisTDA commented on app/views/routes/show.html.erb
> +      <%= form_tag(update_station_railway_station_path(station), method: "put") do %>
Так ведь я то не видел видео следующего урока!!!!!! я то откуда это могу знать!?

2017-05-28 11:29 UTC, iBublik commented on app/views/routes/show.html.erb
> +      <%= form_tag(update_station_railway_station_path(station), method: "put") do %>
Поэтому я выше привел текст задания, в котором сказано что не надо делать веб-интерфейс

2017-05-28 12:29 UTC, vkurennov commented on app/controllers/railway_stations_controller.rb
> +  def update_station
Ну а в самом задании этого ведь нет. А раз нет в задании, то не стоит и делать. Но в целом да, ранее это было в текщуем задании, сейчас немного изменено, поэтому в ветке обсуждение есть, а задания нет. На будущее: ориентируемся на задание, а не на обсуждение. Если возникает вопрос - нужно это делать или нет, можно спросить.

2017-05-28 12:30 UTC, vkurennov commented on app/models/carriage.rb
> +  def set_number
А пропуски в номерах допустимы

2017-05-28 12:30 UTC, vkurennov commented on app/models/railway_station.rb
> +  def update_position(route, position)
Но не в задании...

2017-05-28 12:31 UTC, vkurennov commented on app/views/carriages/compart_carriage.html.erb
> +<%= render 'carriage', carriage: @carriage %>
К сожалению, долго не означает правильно

2017-05-28 12:33 UTC, vkurennov commented on app/views/routes/show.html.erb
> +      <%= form_tag(update_station_railway_station_path(station), method: "put") do %>
Ну ты взял это из обсуждения на форуме, но в самом заднии об этом не сказано. Еще раз: ориентируйся на задание, обсуждение - это все таки доп. информация. В целом то, что сделал больше чем нужно, не проблема, просто это заняло еще больше времени, чем могло бы. Зато в следующем уроке будет проще.

2017-05-28 12:34 UTC, vkurennov commented
Пока задание отклонено. С большинством комментариев Артема согласен. То, что забежал вперед - не страшно, поэтому код из следующего задания можешь оставить. Остальное надо исправить и сдать повторно.

2017-05-28 12:44 UTC, DenisTDA commented on app/controllers/railway_stations_controller.rb
> +  def update_station
Удалять?

2017-05-28 12:44 UTC, DenisTDA commented on app/models/carriage.rb
> +  def set_number
А мое решение не противоречит заданию...

2017-05-28 12:45 UTC, DenisTDA commented on app/models/railway_station.rb
> +  def update_position(route, position)
удалять?

2017-05-28 12:46 UTC, DenisTDA commented on app/views/carriages/compart_carriage.html.erb
> +<%= render 'carriage', carriage: @carriage %>
Это неправильно?

2017-05-28 12:48 UTC, DenisTDA commented
Вот теперь осталось разобраться "что" нужно исправить..

2017-05-28 18:30 UTC, vkurennov commented
пройдись по комментариям с самого начала, там есть что исправить, начиная с опечаток и далее. Коммита с исправлением этих замечаний я не вижу.

2017-05-28 18:30 UTC, vkurennov requested changes

2017-05-28 18:30 UTC, vkurennov commented on app/controllers/carriages_controller.rb
> +      redirect_to @trainб notice: 'Вагон успешно создан'
А где исправление-то?

2017-05-28 18:40 UTC, DenisTDA commented
я пока не коммитил. У среднего сегодня ДР, поэтому исправления завтра отправлю. По вьюхам так и не понял, исправлять или нет. Проще сделать?

2017-05-28 19:07 UTC, iBublik commented
@DenisTDA вьюхи 100% стоит упростить, сейчас слишком запутано получилось.
В остальном - код из следующего занятия можно оставить.

2017-05-28 19:54 UTC, DenisTDA commented
ок. Вьюхи заменю. опечатки исправлю. с методами пока ничего делать не буду. .. Я, видимо, самый тупой в группе, раз задание не понял. привык, когда дают допматериал, то на него надо опираться, а получилось, что он только для меня трудности создал...

2017-05-29 07:11 UTC, vkurennov commented
Бывает. Не переживай.

2017-05-31 21:12 UTC, closed without merging