Task16, edittion II, complit
DenisTDA/tutu pull request #3
Opened 2017-05-31 00:21 UTC by DenisTDA

Сделал точно по заданию (вроде).

2017-05-31 06:38 UTC, iBublik commented on db/migrate/20170512205026_add_seats_to_carriages.rb
> -class AddSeatsToCarriages < ActiveRecord::Migration[5.1]
Миграции из стабильных веток нельзя удалять - при развертывании у нового члена команды это вызовет проблемы

2017-05-31 06:38 UTC, iBublik commented on db/migrate/20170530174923_change_carriages.rb
> +      t.remove :kind
Вот это вызовет креш из-за удаления миграции - будет попытка удаления поля, которого не существует.

2017-05-31 06:38 UTC, iBublik commented on db/migrate/20170530174923_change_carriages.rb
> +    add_column(:carriages, :created_at, :datetime)
Можно в `change_table` дописать `t.timestamps`

2017-05-31 06:38 UTC, iBublik commented on db/migrate/20170530202441_correct_bottom_place_in_carriages.rb
> +    rename_column :carriages, :botoom_place, :bottom_place
Поле с неверным названием было создано в рамках этой фичи, поэтому разумнее откатить ту миграцию, поправить нейминг, и снова накатить. Таким образом, избавляемся от лишней миграции.

2017-05-31 06:38 UTC, iBublik commented on app/models/seats_carriage.rb
> +  validates :bottom_place, :top_place, :side_bottom_place,
А что эта валидация делает?

2017-05-31 06:38 UTC, iBublik commented on app/models/carriage.rb
> +  def set_number
Номер вагона будет меняться при сохранении. Лучше сделать условное присваивание (`self.number ||= ...`).

2017-05-31 08:15 UTC, vkurennov requested changes

2017-05-31 08:15 UTC, vkurennov commented on app/controllers/carriages_controller.rb
> +    named_view = @carriage.type.underscore.to_sym
Суть верная, но можно было это сделать во вьюхе show, рендеря таким образом паршалы, а не отдельные виды для каждого типа вагона. Это дало бы еще такой бонус как вынесение общих частей в один вид, а отличий - в паршалы.

2017-05-31 08:15 UTC, vkurennov commented on app/controllers/carriages_controller.rb
> +    @carriage = Carriage.new(carriage_params).becomes(Carriage)
Здесь becomes не особо нужен, он нужен для редиректа после сохранения. Но можно редирект написать и так: `redirect_to carriages_path(@carriage)`

2017-05-31 08:15 UTC, vkurennov commented on app/models/carriage.rb
> +    train.carriages.each{ |car| numbers << car.number}
Чтобы сразу получить все номера, но при этом не загружать в память вагоны и не перебирать их, можно использовать метод pluck: `train.carriages.pluck(:number)`

2017-05-31 08:15 UTC, vkurennov commented on app/models/carriage.rb
> +    loop do
Не лучше ли использовать цикл с условием?

2017-05-31 08:15 UTC, vkurennov commented on app/models/seats_carriage.rb
> +  validates :bottom_place, :top_place, :side_bottom_place,
Да, действительно, что? presence: false  - это то же самое, что и отсутсвие валидации. Но если валидация не нужна, то мы ее просто не пишем

2017-05-31 08:15 UTC, vkurennov commented on app/views/carriages/economy_carriage.html.erb
> +  <strong>Порядковый номер:</strong>
Если использовать схему с общим видом show и паршалом, то вот эти общие для всех типов вагонов вещи можно вынести. Будет меньше дублирования

2017-05-31 08:18 UTC, DenisTDA commented on db/migrate/20170530174923_change_carriages.rb
> +    add_column(:carriages, :created_at, :datetime)
я так пробовал. Выскакивает ошибка. Гуглил, порекомендовали так сделать.. так работает.

2017-05-31 08:18 UTC, DenisTDA commented on db/migrate/20170530174923_change_carriages.rb
> +      t.remove :kind
Вчера это была основная проблема. Я понимаю, что на рабочей модели так делать нельзя. Когда я откатился на мастер с ветки task16, то миграции, которые были в ветки естественно пропали, а вот физические таблицы остались. Когда начал создавать (вроде бы заново) таблицы и поля, то стали возникать конфликты с существующими полями. Поэтому и спрашивал как можно откатить базу. Ну, и видимо, обрадовался и откатил чуть дальше (можно ведь! :-) ). В моем случае конфликтов не возникло, но я уже знаю что так делать нельзя. С гитом вообще никогда не работал, поэтому еще в стадии познания, ну а это для меня хороший опыт. Я  на двух машинах работаю в разных местах. На одной вообще уронил... базу.. тоже опыт. :-)

2017-05-31 08:35 UTC, DenisTDA commented on app/models/seats_carriage.rb
> +  validates :bottom_place, :top_place, :side_bottom_place,
это я хотел попробовать запретить валидацию на этих полях.. правда не успел посмотреть как работает :-) Идея какая была: во вьюхе мы показываем все поля (есть избыточность), я хотел выводить ошибку при заполнении не относящихся к этому классу полей. (Может так и не правильно... я пробовал, забыл убрать, никак не могу привыкнуть к такому количеству открытых файлов.. надо бы систему придумать работы, так сказать регламент.. ). Потом пришла в голову мысль, что можно с формой редактирования также поступить как и с шоу. Только себя сразу остановил, что опять сверх задания делаю... поэтому не сделал.. но могу :-)

2017-05-31 08:37 UTC, DenisTDA commented on app/models/carriage.rb
> +  def set_number
в первом варианте так и было. я ночью сего сидел и думал: зачем я (self.number ||= ...). сделал?! так как уже дико хотелось спать (а еще на работу!), то сильно задумываться не стал.

2017-05-31 08:41 UTC, DenisTDA commented on app/controllers/carriages_controller.rb
> +    named_view = @carriage.type.underscore.to_sym
я в первый раз в ветке task16 так и сделал.. вам не понравилось.. правда я там не паршелы использовал, а yield. Но мысль была такая. Я согласен, там много повторяющегося кода. Но уже сил ночью не хватило. Я доделаю.

2017-05-31 08:42 UTC, DenisTDA commented on app/controllers/carriages_controller.rb
> +    @carriage = Carriage.new(carriage_params).becomes(Carriage)
учту.

2017-05-31 08:44 UTC, DenisTDA commented on app/models/carriage.rb
> +    train.carriages.each{ |car| numbers << car.number}
! надо запомнить!

2017-05-31 08:47 UTC, DenisTDA commented on app/models/carriage.rb
> +    loop do
я об этом думал. И наверное  да.. лучше. Пока оставил то что точно работает. (:-) хотя цикл с условием тоже "точно" будет работать... :-) )

2017-05-31 08:49 UTC, DenisTDA commented on app/views/carriages/economy_carriage.html.erb
> +  <strong>Порядковый номер:</strong>
переделаю

2017-05-31 08:50 UTC, DenisTDA commented
данный коммит был сделан больше для того, чтобы понять, что я правильно понял и сделал задание (по направлению), все шероховатости доделаю.

2017-05-31 20:46 UTC, DenisTDA commented on app/models/carriage.rb
> +    loop do
Еще раз хочу вернуться к нумерации вагонов. Многие сделали назначение следующего номера за максимальным номером вагонов в поезде. Но если по техническим (стекла ураганом выбило) причинам убрать, например, первые десять вагонов, то при назначении новых 10 вагонов нумерация начнется с 11-го по N+10, т.е. первые вагоны пропали (а билеты уже проданы в 1,2,3,4,5 и т.д. вагоны). Ну это так.. лирика. Не посмотрел у других, но у меня возникла проблема: 
Если поставить условное присвоение, то при изменении поезда у вагона, вагон в новый поезд попадет уже с назначенным номером и может возникнуть конфликтная ситуация, а при обычном присвоении, если меняем количество мест и не меняем поезд, то меняется нумерация вагона и он "убегает" в хвост поезда, что не надо.
Номер должен меняться при редактировании если другой поезд...по идеи надо в экшене edit запомнить id поезда и передать это значение в update, чтобы потом можно было поинтересоваться сменился поезд или нет.. только как это сделать? и как передать в метод?

2017-05-31 20:58 UTC, DenisTDA commented on app/models/carriage.rb
> +    loop do
кстати, при именовании станции там тоже неоднозначность...

2017-06-01 05:41 UTC, iBublik commented on app/models/carriage.rb
> +    numbers = []
Эта строка не имеет смысла, `pluck` всегда массив возвращает

2017-06-01 07:55 UTC, vkurennov approved these changes

2017-06-01 08:05 UTC, DenisTDA commented on app/models/carriage.rb
> +    numbers = []
Институтская привычка не отпускает .. :-)

2017-06-01 12:16 UTC, merged