Task18
DenisTDA/tutu pull request #5
Opened 2017-06-20 20:04 UTC by DenisTDA

2017-06-21 08:07 UTC, iBublik requested changes

2017-06-21 08:07 UTC, iBublik commented on app/controllers/admin/base_controller.rb
> +  def configure_permitted_parameters
У тебя ведь есть этот метод в ApplicationController, зачем его тут переопределять?

2017-06-21 08:07 UTC, iBublik commented on app/controllers/admin/tickets_controller.rb
> +    @start_station = RailwayStation.find(params[:start_station_id])
Можно так - `@start_station, @end_station = RailwayStation.find(params.values_at(:start_station_id, :end_station_id))`

2017-06-21 08:07 UTC, iBublik commented on app/controllers/admin/tickets_controller.rb
> +  def set_environ
Не понимаю имя метода

2017-06-21 08:07 UTC, iBublik commented on app/controllers/admin/tickets_controller.rb
> +    @start_station = RailwayStation.find(@ticket.start_station_id)
Зачем все это делать ручками? `@ticket.train, @ticker.start_station, @ticket.end_station`

2017-06-21 08:07 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +  before_action :authenticate_user!, only: [:create, :update, :index]
Почему только эти экшены? Этот контроллер предназначен только для залогиненных пользователей

2017-06-21 08:07 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +  before_action :set_ticket, only: %i[ show edit ]
А как же `update` и `destroy`?

2017-06-21 08:07 UTC, iBublik commented on app/controllers/tickets_controller.rb
>      @ticket = Ticket.find(params[:id])
Билет должен искаться среди билетов текущего пользователя. Иначе зная id можно управлять билетами другого пользователя

2017-06-21 08:07 UTC, iBublik commented on app/controllers/tickets_controller.rb
>  class TicketsController < ApplicationController
Из разрешенных параметров нужно убрать `user_id` - билеты привязывается к залогиненному юзеру, а не из параметров приходит

2017-06-21 08:07 UTC, iBublik commented on app/controllers/tutu_controller.rb
> +class TutuController < ApplicationController
Этот контроллер не нужен

2017-06-21 08:07 UTC, iBublik commented on app/models/ticket.rb
> +    number.nil? || Ticket.pluck(:number).count(number) > 1 || number == ''
`number.blank? || Ticket.exists?(number: number)`

2017-06-21 08:07 UTC, iBublik commented on app/models/user.rb
> +  # validates :name, presence: true
Неиспользуемый код не надо оставлять в комментариях

2017-06-21 08:07 UTC, iBublik commented on app/models/ticket.rb
> +    Ticket.last ? self.number = "Ekb-66-01-#{Ticket.last.id + 1}" : self.number = '1'
Плохо понимаю логику этого метода (кажется, не в первый раз :)). Почему уникальный номер не генерится для самого первого поезда? Может так логичнее? `self.number = "Ekb-66-01-#{Ticket.maximum(:id).to_i + 1}"`

2017-06-21 08:07 UTC, iBublik commented on app/views/admin/railway_stations/_railway_station.html.erb
> +  <td><%= link_to 'Edit', edit_admin_railway_station_path(railway_station) %></td>
Чистое ИМХО - надо придерживаться одного стиля роут хелперов. Я за более явные `admin_railway_station_path(railway_station)` - не люблю все эти массивы :)

2017-06-21 08:07 UTC, iBublik commented on app/views/admin/tickets/_form.html.erb
> +    <%= f.hidden_field :number, value: ticket.number %>
А зачем это поле передавать через хидден филд? Все равно ведь оно на бэке генерится

2017-06-21 08:07 UTC, iBublik commented on config/routes.rb
> +    resources :lists, only: [:index]
Обычно для такого делают `resource :dashboard`

2017-06-21 08:07 UTC, iBublik commented on config/routes.rb
> +  root 'tutu#index'
Рутом лучше сделать страницу поиска

2017-06-21 08:07 UTC, iBublik commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(resource)
Не заметил приветствия пользователя после входа

2017-06-21 13:17 UTC, DenisTDA commented on app/controllers/admin/tickets_controller.rb
> +    @start_station = RailwayStation.find(params[:start_station_id])
наверно можно.. но пока для меня не очевидно.. :-) делаю с позиций своих знаний.

2017-06-21 13:19 UTC, DenisTDA commented on app/controllers/admin/tickets_controller.rb
> +    @start_station = RailwayStation.find(@ticket.start_station_id)
забываю про связи..

2017-06-21 13:24 UTC, DenisTDA commented on app/controllers/tickets_controller.rb
> +  before_action :set_ticket, only: %i[ show edit ]
update  - не предусмотрен условием задачи.
про destroy  забыл...

2017-06-21 13:25 UTC, DenisTDA commented on app/controllers/tutu_controller.rb
> +class TutuController < ApplicationController
я,видимо, что-то не так делал, но без него не работало.

2017-06-21 13:27 UTC, DenisTDA commented on app/models/ticket.rb
> +    number.nil? || Ticket.pluck(:number).count(number) > 1 || number == ''
угу. Но опять для меня не очевидно. Пока для меня такие конструкции сложны (да и не знаю я их)

2017-06-21 13:30 UTC, DenisTDA commented on app/models/ticket.rb
> +    Ticket.last ? self.number = "Ekb-66-01-#{Ticket.last.id + 1}" : self.number = '1'
Про поезд не понял..

2017-06-21 13:33 UTC, DenisTDA commented on app/views/admin/railway_stations/_railway_station.html.erb
> +  <td><%= link_to 'Edit', edit_admin_railway_station_path(railway_station) %></td>
:-) человек ленив.. что короче писать, то и выбираем. Массив короче, тем более в скринкасте показано...

2017-06-21 13:34 UTC, DenisTDA commented on app/views/admin/tickets/_form.html.erb
> +    <%= f.hidden_field :number, value: ticket.number %>
это я перегрелся..;-)

2017-06-21 13:36 UTC, DenisTDA commented on config/routes.rb
> +  root 'tutu#index'
хорошо

2017-06-21 13:36 UTC, DenisTDA commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(resource)
тоже забыл... добавлю

2017-06-21 13:39 UTC, DenisTDA commented
стало тяжело контролировать множество файлов. После добавления devise многое пришлось переносить добавлять исправлять, ну и понятно, что когда в первый раз такое делаешь, что-то не усмотришь не поймешь.. ошибок много вылазить, начинаешь с ними бороться, делаешь новые..

2017-06-21 13:43 UTC, iBublik commented on app/controllers/admin/tickets_controller.rb
> +    @start_station = RailwayStation.find(params[:start_station_id])
Ну, надо вперед двигаться и пробовать новое :)

2017-06-21 13:44 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +  before_action :set_ticket, only: %i[ show edit ]
Тогда зачем edit? Он не имеет смысла без update

2017-06-21 13:46 UTC, iBublik commented on app/models/ticket.rb
> +    Ticket.last ? self.number = "Ekb-66-01-#{Ticket.last.id + 1}" : self.number = '1'
Билета*

2017-06-21 13:50 UTC, iBublik commented on app/models/ticket.rb
> +    number.nil? || Ticket.pluck(:number).count(number) > 1 || number == ''
Я предлагаю вариант лаконичнее, понятнее и эффективнее - можно это не использовать, но ознакомиться стоит :) `blank?` объединяет проверку на `nil` и пустую строку. С exists я промахнулся, тут правильнее будет использовать `count` - `Ticket.where(number: number).count`

2017-06-21 17:22 UTC, DenisTDA commented on app/controllers/admin/tickets_controller.rb
> +    @start_station = RailwayStation.find(params[:start_station_id])
Я только "за"! только о новом знать еще надо, что оно вообще существует. Читая буквари не находишь изысканных решений, а читая форумы - не всегда понимаешь о чем речь.. Легче, когда есть опыт хотя бы в других языках.. к сожалению, у меня его нет.. поэтому многие решения исходят исключительно из моих знаний. как-то так. Но пытаюсь.. разбираюсь.. долго только получается..

2017-06-21 17:24 UTC, DenisTDA commented on app/controllers/tickets_controller.rb
> +  before_action :set_ticket, only: %i[ show edit ]
лишний код..

2017-06-21 17:45 UTC, DenisTDA commented on app/models/ticket.rb
> +    number.nil? || Ticket.pluck(:number).count(number) > 1 || number == ''
с blank? понятно.. Ticket.where(number: number).count получается тоже самое, только с помощью хелперов... но условие все равно должно остаться: Ticket.where(number: number).count > 1 .. так ведь?

2017-06-21 17:46 UTC, DenisTDA commented on app/models/ticket.rb
> +    Ticket.last ? self.number = "Ekb-66-01-#{Ticket.last.id + 1}" : self.number = '1'
ну да.. согласен.

2017-06-21 19:43 UTC, DenisTDA commented on app/controllers/admin/base_controller.rb
> +  def configure_permitted_parameters
лишний код... экспериментировал, когда не получалось стронг параметры изменить.

2017-06-21 20:01 UTC, DenisTDA commented on app/controllers/admin/tickets_controller.rb
> +  def set_environ
фантазии не хватило.. вообще хотел назвать environment (окружение билета) криво конечно.

2017-06-21 20:10 UTC, DenisTDA commented on app/controllers/tickets_controller.rb
>      @ticket = Ticket.find(params[:id])
:-) много мне еще практиковаться надо... забывается про такие моменты..

2017-06-21 20:15 UTC, DenisTDA commented on app/models/user.rb
> +  # validates :name, presence: true
вот тут я не уверен, что эти поля надо удалять..

2017-06-21 20:18 UTC, DenisTDA commented on app/views/admin/railway_stations/_railway_station.html.erb
> +  <td><%= link_to 'Edit', edit_admin_railway_station_path(railway_station) %></td>
А зачем в нужно передавать роут хелперу сам объект? вот этот момент совсем не понял.

2017-06-21 21:21 UTC, closed without merging

2017-06-21 21:22 UTC, DenisTDA commented
переработал

2017-06-22 07:38 UTC, iBublik commented on app/controllers/admin/tickets_controller.rb
> +    @start_station = RailwayStation.find(params[:start_station_id])
@DenisTDA так я и пытаюсь передать лучшие практики :) Если бы это было единственным комментарием, то задание бы не стал отклонять, т.к. это просто рекомендация

2017-06-22 07:44 UTC, iBublik commented on app/models/ticket.rb
> +    number.nil? || Ticket.pluck(:number).count(number) > 1 || number == ''
@DenisTDA не то же самое - там подсчет идет в БД. Это намного эффективнее

2017-06-22 07:46 UTC, iBublik commented on app/views/admin/railway_stations/_railway_station.html.erb
> +  <td><%= link_to 'Edit', edit_admin_railway_station_path(railway_station) %></td>
@DenisTDA ну ведь у нас в url для показа станции используется ее id. А id из модели берется, поэтому ее нужно в хелпер передать