Task18
DenisTDA/tutu pull request #6
Opened 2017-06-21 21:23 UTC by DenisTDA

second edition

2017-06-22 07:34 UTC, iBublik commented
@DenisTDA не нужно ПР закрывать перед повторной сдачей. Неудобно отслеживать какие изменения были сделаны

2017-06-22 07:52 UTC, iBublik requested changes

2017-06-22 07:52 UTC, iBublik commented on app/controllers/admin/tickets_controller.rb
> +    @end_station, @start_station = RailwayStation.find(params.values_at(:start_station_id, :end_station_id))
Разобрался как это работает?

2017-06-22 07:52 UTC, iBublik commented on app/controllers/searches_controller.rb
> + before_action :authenticate_user!, only: [:create]
А почему тут аутентификация вдруг? Поиск у нас может и неззалогиненный пользователь делать.

2017-06-22 07:52 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +  def redirect_to_admin
Где это используется?

2017-06-22 07:52 UTC, iBublik commented on app/controllers/admin/lists_controller.rb
> +class Admin::ListsController < Admin::BaseController
Это еще нужно?

2017-06-22 07:52 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +  before_action :authenticate_user!, only: [:create, :index]
Опять же, почему только эти экшены? Какой смысл незалогиненному юзеру давать доступ к new, если он все равно форму отправить не сможет :)

2017-06-22 07:52 UTC, iBublik commented on app/controllers/tickets_controller.rb
> +  before_action :authenticate_user!, only: [:create, :index]
С destroy та же история

2017-06-22 07:52 UTC, iBublik commented on app/models/user.rb
> +  # validates :name, presence: true
Оставь эти валидации. Devise использует эту модель, так что валидации будут работать и в нем

2017-06-22 07:52 UTC, iBublik commented on config/routes.rb
> +    resources :users
Можно просто в `namespace :admin`  это перенести, будет тот же результат

2017-06-22 07:52 UTC, iBublik commented on Gemfile
> +gem 'devise'
Отступ :)

2017-06-22 07:52 UTC, iBublik commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(resource)
Приветствия пользователя все равно не вижу :(

2017-06-22 19:05 UTC, DenisTDA commented on app/controllers/admin/tickets_controller.rb
> +    @end_station, @start_station = RailwayStation.find(params.values_at(:start_station_id, :end_station_id))
Интуитивно понятно, что здесь происходит. Но хотелось бы что-то вроде того, как описан букварь по руби. Когда у классов прописаны все методы(ну или большинство из них) в справочной форме. По params тоже не мешало бы знать...

2017-06-22 20:05 UTC, DenisTDA commented on app/controllers/searches_controller.rb
> + before_action :authenticate_user!, only: [:create]
исправил

2017-06-22 20:06 UTC, DenisTDA commented on app/controllers/tickets_controller.rb
> +  before_action :authenticate_user!, only: [:create, :index]
исправил

2017-06-22 20:07 UTC, DenisTDA commented on app/controllers/tickets_controller.rb
> +  def redirect_to_admin
сейчас используется

2017-06-22 20:07 UTC, DenisTDA commented on app/controllers/admin/lists_controller.rb
> +class Admin::ListsController < Admin::BaseController
нет.. убрал.

2017-06-22 20:07 UTC, DenisTDA commented on app/models/user.rb
> +  # validates :name, presence: true
сделано

2017-06-22 20:13 UTC, DenisTDA commented on Gemfile
> +gem 'devise'
не понял.. это ты про что?

2017-06-22 20:16 UTC, DenisTDA commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(resource)
я не понял как надо делать.. я сделал через application.html.erb

2017-06-22 20:19 UTC, DenisTDA commented
iBublik commented 13 hours ago
@DenisTDA не нужно ПР закрывать перед повторной сдачей. Неудобно отслеживать какие изменения были сделаны

я не совсем понял, как поступать, если задание не принято. Я делаю исправления, коммичу... а далее создавать надо новый пулреквест? без закрытия старого? или как?

2017-06-22 20:22 UTC, DenisTDA commented on config/routes.rb
> +    resources :users
в смысле ресурс?

2017-06-24 06:30 UTC, iBublik commented
@DenisTDA все правильно сделал - просто делаешь коммиты в ту же ветку, они подтянутся в PR. Главное не закрывай его :)

2017-06-24 06:39 UTC, iBublik commented on Gemfile
> +gem 'devise'
Ну отступы слетели - должно быть 2 пробела

2017-06-24 06:39 UTC, iBublik commented on app/controllers/searches_controller.rb
> + # before_action :authenticate_user!, only: [:create]
Комментарий долой

2017-06-24 06:39 UTC, iBublik commented on config/routes.rb
> +    resources :users
У тебя уже есть `namespace :admin` - если поместить `resources :users` туда, то `scope` можно убрать

2017-06-24 09:21 UTC, vkurennov approved these changes

2017-06-24 12:43 UTC, DenisTDA commented on config/routes.rb
> +    resources :users
понял.
Когда в инете ищешь ответ, находишь примеры к конкретным ситуациям, пытаюсь их применить к своему вопросу. Видимо нашел такое решение.

2017-06-24 12:44 UTC, DenisTDA commented on Gemfile
> +gem 'devise'
Странно... у меня нормально отображается.. и настройки все стоят нормально.. перепроверю

2017-06-24 12:44 UTC, DenisTDA commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(resource)
На счет приветствия так и не понял.. Как надо было правильно делать?

2017-06-24 12:46 UTC, DenisTDA commented on app/controllers/searches_controller.rb
> + # before_action :authenticate_user!, only: [:create]
ага.. тоже нашел пару закомментированных строк , уже исправил. в смысле удалил

2017-06-24 12:47 UTC, merged